### PR TITLE
R&D

### PR DESCRIPTION
**Pull request by cyrusmsk**
Added examples for R and D languages.
R is interpreted lang, while D is compiled one. So it should be in the same group with Swift and Rust.

### CODE REVIEW

**Comment by cyrusmsk** [comment]
Hi @ad-si 
I think the PR is ready.
Unfortunately dmd compiler is not ready for ARM yet. And it has much faster compilation, which is more suitable for scripting usage. But LDC should be fine as well.

**Comment by cyrusmsk** [comment]
Ping @ad-si 
Let me know if you think something need to be fixed in the code
Happy holidays!

**Comment by ad-si** [comment]
Nice, thanks!
Happy Holidays! 😊

**Comment by cyrusmsk** [comment]
Hm I can see that the Actions have errors now because of D. But I'm not sure what is the reason of that.
I've tested the code example locally and it worked

**Comment by cyrusmsk** [comment]
I found an issue - I've made a separate PR.
It seems somehow rdmd requried for D code installed with dtools

**Pull request merged**
